from django.urls import path, include
from projeto_final import urls
from . import views

urlpatterns = [
    path('profile/propertiesManagement/listingEditing/<int:property_id>', views.listing_editing_view, name='listingEditing'),
    path('profile/propertiesManagement/propertyEditing/<int:property_id>', views.property_editing_view, name='propertyEditing'),
    path('profile/propertiesManagement/bedroomsEditing/<int:property_id>', views.bedrooms_editing_view, name='bedroomsEditing'),
    path('profile/propertiesManagement/deleteBedroom/<int:property_id>/<int:bedroom_id>', views.bedroom_delete_view, name='removeBedroom'),  
    path('profile/propertiesManagement/deleteBedroom/<int:property_id>/', views.bedroom_delete_view, name='removeBedroom'),
    path('profile/propertiesManagement/deleteBathroom/<int:property_id>/<int:bathroom_id>', views.bathroom_delete_view, name='removeBathroom'),    
    path('profile/propertiesManagement/deleteBathroom/<int:property_id>/', views.bathroom_delete_view, name='removeBathroom'),   
    path('profile/propertiesManagement/bathroomsEditing/<int:property_id>', views.bathrooms_editing_view, name='bathroomsEditing'),
    path('profile/propertiesManagement/kitchensEditing/<int:property_id>', views.kitchens_editing_view, name='kitchensEditing'),
    path('profile/propertiesManagement/deleteKitchen/<int:property_id>/<int:kitchen_id>', views.kitchen_delete_view, name='removeKitchen'),    
    path('profile/propertiesManagement/deleteKitchen/<int:property_id>/', views.kitchen_delete_view, name='removeKitchen'),
    path('profile/propertiesManagement/livingroomsEditing/<int:property_id>', views.livingrooms_editing_view, name='livingroomsEditing'),
    path('profile/propertiesManagement', views.properties_management_view, name='propertiesManagement'),
    path('addProperty', views.introduce_property_view, name='addProperty'),
    path('addProperty/bedroom/', views.introduce_property_view, name='addBedroom'),
    path('addProperty/bathroom/', views.introduce_property_view, name='addBathroom'),
    path('addProperty/kitchen/', views.introduce_property_view, name='addKitchen'),
    path('addProperty/livingroom/', views.introduce_property_view, name='addLivingroom'),
    path('addProperty/listing/', views.introduce_property_view, name='addListing'),
    #path('login', views.login_view, name='login_view'),
    #path('logout', views.logout_view, name='logout_view'),
    #path('register', views.register_view, name='register_view'),
    path('profile', views.profile, name = 'profile'),
    path('search', views.search, name='search'),
    path('', views.index, name='index'),
    path('notificationsTenant', views.notificationsTenant, name='notificationsTenant'),
    path('notificationsLandlord', views.notificationsLandlord, name='notificationsLandlord'),
    path('listing/application', views.create_request, name='create_request'),
    path('listing/<int:listing_id>', views.listing, name='listing'),
    path('listing/requestAccepted/<int:request_id>', views.accept_request, name='accept_request'),
    path('listing/requestDenied/<int:request_id>', views.deny_request, name='deny_request'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/changeToRegister', views.changeToRegister, name='changeToRegister'),
    
]
