# Generated by Django 3.1.2 on 2021-02-22 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('floor_area', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('garden', models.BooleanField()),
                ('garage', models.BooleanField()),
                ('street_parking', models.BooleanField()),
                ('internet', models.BooleanField()),
                ('electricity', models.BooleanField()),
                ('water', models.BooleanField()),
                ('gas', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('overnight_visits', models.BooleanField()),
                ('cleaning_services', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('lord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.app_user')),
                ('lord_type', models.CharField(default='Particular', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainApp.app_user')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet', models.BooleanField()),
                ('sink', models.BooleanField()),
                ('shower', models.BooleanField()),
                ('window', models.BooleanField()),
                ('bathtub', models.BooleanField()),
                ('privateOrshared', models.BooleanField()),
                ('associatedProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.property')),
            ],
        ),
        migrations.CreateModel(
            name='App_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.landlord'),
        ),
    ]
