# Generated by Django 3.1.2 on 2021-02-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='caralho',
        ),
    ]
