# Generated by Django 3.1.7 on 2021-04-17 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=280)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='agreement',
            name='last_invoice_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('agreement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.agreement')),
                ('agreement_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.agreement_request')),
            ],
        ),
    ]
