# Generated by Django 3.1.7 on 2021-05-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='is_read',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
