# Generated by Django 3.1.7 on 2021-02-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bathroom',
            old_name='window',
            new_name='b_window',
        ),
        migrations.RenameField(
            model_name='bedroom',
            old_name='balcony',
            new_name='be_balcony',
        ),
        migrations.RenameField(
            model_name='bedroom',
            old_name='chairs',
            new_name='be_chairs',
        ),
        migrations.RenameField(
            model_name='bedroom',
            old_name='desk',
            new_name='be_desk',
        ),
        migrations.RenameField(
            model_name='bedroom',
            old_name='sofa',
            new_name='be_sofa',
        ),
        migrations.RenameField(
            model_name='bedroom',
            old_name='sofa_bed',
            new_name='be_sofa_bed',
        ),
        migrations.RenameField(
            model_name='bedroom',
            old_name='window',
            new_name='be_window',
        ),
        migrations.RenameField(
            model_name='kitchen',
            old_name='balcony',
            new_name='k_balcony',
        ),
        migrations.RenameField(
            model_name='kitchen',
            old_name='chairs',
            new_name='k_chairs',
        ),
        migrations.RenameField(
            model_name='kitchen',
            old_name='table',
            new_name='k_table',
        ),
        migrations.RenameField(
            model_name='kitchen',
            old_name='window',
            new_name='k_window',
        ),
        migrations.RenameField(
            model_name='livingroom',
            old_name='balcony',
            new_name='l_balcony',
        ),
        migrations.RenameField(
            model_name='livingroom',
            old_name='chairs',
            new_name='l_chairs',
        ),
        migrations.RenameField(
            model_name='livingroom',
            old_name='desk',
            new_name='l_desk',
        ),
        migrations.RenameField(
            model_name='livingroom',
            old_name='sofa',
            new_name='l_sofa',
        ),
        migrations.RenameField(
            model_name='livingroom',
            old_name='sofa_bed',
            new_name='l_sofa_bed',
        ),
        migrations.RenameField(
            model_name='livingroom',
            old_name='table',
            new_name='l_table',
        ),
        migrations.RenameField(
            model_name='livingroom',
            old_name='window',
            new_name='l_window',
        ),
    ]
