# Generated by Django 3.1.7 on 2021-02-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='kitchen',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='chairs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='microwave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='table',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_cover', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.imagealbum')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ListingAlbum', to='mainApp.imagealbum'),
        ),
    ]
