# Generated by Django 3.1.7 on 2021-03-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=14, default=200.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=14, default=100.0, max_digits=20),
            preserve_default=False,
        ),
    ]
