# Generated by Django 3.1.7 on 2021-05-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='reviewd',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
