# Generated by Django 3.1.7 on 2021-04-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rich_text_message',
            old_name='messageLandlord',
            new_name='message',
        ),
    ]
