# Generated by Django 3.1.2 on 2021-02-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='lord_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.app_user'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ten_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.app_user'),
        ),
    ]
