# Generated by Django 3.1.2 on 2021-02-23 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210223_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_gender', models.CharField(max_length=20)),
                ('monthly_payment', models.IntegerField()),
                ('availability_starts', models.DateField()),
                ('availability_ending', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('security_deposit', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='property',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='cleaning_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='gas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='overnight_visits',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='water',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Room_listing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.listing')),
                ('associated_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.bedroom')),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='r_main', to='mainApp.listing')),
            ],
            bases=('mainApp.listing',),
        ),
        migrations.CreateModel(
            name='Property_listing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.listing')),
                ('associated_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.property')),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_main', to='mainApp.listing')),
            ],
            bases=('mainApp.listing',),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startsDate', models.DateField()),
                ('endDate', models.DateField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.landlord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.tenant')),
                ('associated_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.property_listing')),
                ('associated_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.room_listing')),
            ],
        ),
    ]
