# Generated by Django 2.1.5 on 2021-03-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210306_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='associated_property',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='associated_room',
        ),
        migrations.RemoveField(
            model_name='agreement_request',
            name='associated_property',
        ),
        migrations.RemoveField(
            model_name='agreement_request',
            name='associated_room',
        ),
        migrations.AddField(
            model_name='agreement',
            name='associated_property_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Property_listing'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='associated_room_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Room_listing'),
        ),
        migrations.AddField(
            model_name='agreement_request',
            name='associated_property_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Property_listing'),
        ),
        migrations.AddField(
            model_name='agreement_request',
            name='associated_room_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Room_listing'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms_num',
            field=models.IntegerField(default=1),
        ),
    ]
