# Generated by Django 3.1.2 on 2021-02-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210217_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='isVerified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
