# Generated by Django 3.1.7 on 2021-05-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_incidence_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
