# Generated by Django 3.1.7 on 2021-03-24 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement_request',
            name='dateOfRequest',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 22, 43, 44, 901429, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
