# Generated by Django 3.1.7 on 2021-04-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210417_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_line',
            name='invoice_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.invoice'),
            preserve_default=False,
        ),
    ]
