# Generated by Django 3.1.7 on 2021-02-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210227_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startsDate', models.DateField()),
                ('endDate', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('associated_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.property_listing')),
                ('associated_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.room_listing')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.landlord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.tenant')),
            ],
        ),
    ]
