# Generated by Django 3.1.7 on 2021-03-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210306_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='associated_property',
            new_name='associated_property_listing',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='associated_room',
            new_name='associated_room_listing',
        ),
        migrations.RenameField(
            model_name='agreement_request',
            old_name='associated_property',
            new_name='associated_property_listing',
        ),
        migrations.RenameField(
            model_name='agreement_request',
            old_name='associated_room',
            new_name='associated_room_listing',
        ),
    ]
