# Generated by Django 3.1.7 on 2021-05-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_agreement_reviewd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='reviewd',
            new_name='reviewed',
        ),
    ]