# Generated by Django 2.1.5 on 2021-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210302_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='lock',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
