# Generated by Django 2.1.5 on 2021-03-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210307_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms_num',
            field=models.IntegerField(),
        ),
    ]
