# Generated by Django 3.1.7 on 2021-05-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210515_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]