# Generated by Django 3.1.7 on 2021-05-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210507_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reviews', models.IntegerField()),
                ('conservation', models.DecimalField(decimal_places=19, max_digits=20)),
                ('services', models.DecimalField(decimal_places=19, max_digits=20)),
                ('access', models.DecimalField(decimal_places=19, max_digits=20)),
                ('neighbours', models.DecimalField(decimal_places=19, max_digits=20)),
                ('tenants', models.DecimalField(decimal_places=19, max_digits=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.property')),
            ],
        ),
    ]
