# Generated by Django 3.1.7 on 2021-05-18 22:04

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210515_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='image',
            field=models.ImageField(default=None, upload_to=mainApp.models.get_upload_path),
            preserve_default=False,
        ),
    ]