# Generated by Django 3.1.2 on 2021-04-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210324_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(default='Apartment', max_length=20),
            preserve_default=False,
        ),
    ]
