# Generated by Django 3.1.2 on 2021-02-19 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210217_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='isVerified',
        ),
    ]
