# Generated by Django 3.1.7 on 2021-05-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_propertyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='lord_review',
            field=models.DecimalField(decimal_places=19, default=5, max_digits=20),
        ),
        migrations.AddField(
            model_name='landlord',
            name='lord_review_num',
            field=models.IntegerField(default=0),
        ),
    ]
