# Generated by Django 3.1.7 on 2021-05-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210516_1925'),
        ('mainApp', '0004_app_user_image'),
    ]

    operations = [
    ]
