# Generated by Django 3.1.7 on 2021-04-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210418_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='address',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
