# Generated by Django 3.1.6 on 2021-02-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_app_user_isverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('floor_area', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('garden', models.BooleanField()),
                ('garage', models.BooleanField()),
                ('street_parking', models.BooleanField()),
                ('internet', models.BooleanField()),
                ('electricity', models.BooleanField()),
                ('water', models.BooleanField()),
                ('gas', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('overnight_visits', models.BooleanField()),
                ('cleaning_services', models.BooleanField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet', models.BooleanField()),
                ('sink', models.BooleanField()),
                ('shower', models.BooleanField()),
                ('window', models.BooleanField()),
                ('bathtub', models.BooleanField()),
                ('privateOrshared', models.BooleanField()),
                ('associatedProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.property')),
            ],
        ),
    ]
