# Generated by Django 3.1.7 on 2021-04-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_property_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
