# Generated by Django 3.1.7 on 2021-04-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_tenant_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_search',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='min_search',
            field=models.IntegerField(default=500),
        ),
    ]
