# Generated by Django 3.1.7 on 2021-04-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_app_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
