# Generated by Django 3.1.7 on 2021-05-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_merge_20210520_0049'),
        ('mainApp', '0006_auto_20210519_1721'),
    ]

    operations = [
    ]
