# Generated by Django 3.1.7 on 2021-04-20 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_agreement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='associated_property_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.property_listing'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='associated_room_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.room_listing'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.landlord'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.tenant'),
        ),
        migrations.AlterField(
            model_name='agreement_request',
            name='associated_property_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.property_listing'),
        ),
        migrations.AlterField(
            model_name='agreement_request',
            name='associated_room_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.room_listing'),
        ),
        migrations.AlterField(
            model_name='agreement_request',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.landlord'),
        ),
        migrations.AlterField(
            model_name='agreement_request',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.tenant'),
        ),
    ]
