# Generated by Django 3.1.7 on 2021-05-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_merge_20210520_1505'),
        ('mainApp', '0007_merge_20210520_1452'),
    ]

    operations = [
    ]
