# Generated by Django 3.1.7 on 2021-04-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20210420_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement_request',
            name='checkRead',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
