# Generated by Django 3.1.6 on 2021-06-09 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_merge_20210520_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='nif',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(100000000)]),
        ),
    ]
