# Generated by Django 3.1.7 on 2021-04-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_agreement_request_checkread'),
        ('mainApp', '0010_invoice_paid'),
    ]

    operations = [
    ]
