# Generated by Django 3.1.7 on 2021-04-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_merge_20210421_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.agreement')),
            ],
        ),
    ]
