# Generated by Django 3.1.7 on 2021-04-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_payment_warning_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_warning',
            name='sent',
        ),
        migrations.AddField(
            model_name='payment_warning',
            name='invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.invoice'),
            preserve_default=False,
        ),
    ]
