# Generated by Django 3.1.7 on 2021-04-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.agreement'),
        ),
    ]
