# Generated by Django 3.1.7 on 2021-04-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_refund_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='dateOfRequest',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
