# Generated by Django 3.1.2 on 2021-04-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_receipt'),
        ('mainApp', '0017_auto_20210423_2250'),
        ('mainApp', '0011_merge_20210421_0123'),
        ('mainApp', '0018_refund_dateofrequest'),
    ]

    operations = [
    ]
