# Generated by Django 3.1.7 on 2021-04-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='checkReadTenant',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_warning',
            name='checkReadTenant',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
