# Generated by Django 3.1.7 on 2021-04-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_auto_20210426_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_time', models.DateField()),
                ('description', models.CharField(max_length=280)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.chat')),
                ('causes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.cause')),
            ],
        ),
    ]
