# Generated by Django 3.1.7 on 2021-04-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_cause_incidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='grouds_for_termination',
            field=models.BooleanField(null=True),
        ),
    ]
