# Generated by Django 3.1.7 on 2021-04-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_incidence_grouds_for_termination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.agreement'),
        ),
    ]
