# Generated by Django 3.1.7 on 2021-04-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_auto_20210428_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidence',
            old_name='causes',
            new_name='causes_id',
        ),
    ]
