# Generated by Django 3.1.7 on 2021-04-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_auto_20210428_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidence',
            old_name='causes_id',
            new_name='causes',
        ),
    ]
