# Generated by Django 3.1.7 on 2021-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_auto_20210428_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='causes',
        ),
        migrations.AddField(
            model_name='incidence',
            name='causes',
            field=models.ManyToManyField(to='mainApp.Cause'),
        ),
    ]
